import sqlite3
from Crypto.Cipher import AES
from Crypto.Random import get_random_bytes
import base64
import os


#This script encrypts a given plaintext password using the AES encryption algorithm in EAX mode from the PyCryptodome library.
#The encryption process begins by creating a new AES cipher object with a predefined AES_KEY. EAX mode is used for encryption, 
#A unique nonce (number used once) is automatically generated by the cipher for each encryption session,
# ensuring that even if the same password is encrypted multiple times, the resulting ciphertext will be different. 
#The plaintext password is then encrypted and authenticated, and the nonce is added to the front of the ciphertext. 
#then the combined nonce and ciphertext are base64-encoded and returned as a string, making it ready for storage 

# Function to load or generate AES key
def load_or_generate_key():
    key_file = "aes_key.key"
    
    # If key file exists, load it
    if os.path.exists(key_file):
        with open(key_file, "rb") as f:
            return f.read()
    
    # Otherwise, generate a new key and save it
    new_key = get_random_bytes(32)  # AES-256 key
    with open(key_file, "wb") as f:
        f.write(new_key)
    return new_key

AES_KEY = load_or_generate_key()  # Load existing or create a new key

# Encrypts the password using AES in EAX mode, returning the combined random_value and ciphertext as a base64-encoded string.
def encrypt_password(plain_password):
    """Encrypts the password using AES."""
    cipher = AES.new(AES_KEY, AES.MODE_EAX)
    nonce = cipher.nonce
    ciphertext, tag = cipher.encrypt_and_digest(plain_password.encode())
    return base64.b64encode(nonce + ciphertext).decode()

# Hardcoded password
password = "PasswordTest!"
encrypted_password = encrypt_password(password)

# Print encrypted password
print(f"Encrypted Password (AES): {encrypted_password}")

# Connect to SQLite
conn = sqlite3.connect("password_manager.db")
cursor = conn.cursor()

# Create table if it doesn’t exist
cursor.execute("""
    CREATE TABLE IF NOT EXISTS passwords (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        Account_type TEXT NOT NULL,
        username TEXT NOT NULL,
        encrypted_password TEXT NOT NULL
    )
""")

# Insert encrypted password
cursor.execute("INSERT INTO passwords (Account_type, username, encrypted_password) VALUES (?, ?, ?)", 
               ("examples.com", "user1234", encrypted_password))

# Commit & close
conn.commit()
conn.close()

print("Encrypted password has been stored in the database successfully!")
